name: GitHub Actions Checks
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  pull_request:
    types: [opened, reopened]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: Check es-lint rules
        run: npm run lint
